services:
  - type: web
    name: mi-app
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"  # Cambiar por tu comando si usás Django
    envVars:
      - key: DEBUG
        value: "False"